-- =====================================================================
-- V11__add_event_dismissals.sql
--
-- Antes, cualquiera veía los botones "Editar" y "Eliminar" en CUALQUIER
-- evento, los hubiera creado o no (el backend sí lo bloqueaba con un
-- 403, pero la persona lo descubría solo al pulsar el botón). Lo que
-- Alexandra pide es: solo quien creó el evento debe ver esos botones;
-- para el resto, un botón de "quitar de mi vista" que oculta el evento
-- SOLO en su propia lista, sin borrar el evento real para nadie más.
-- =====================================================================

CREATE TABLE event_dismissals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    family_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_dismissal_event FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE,
    CONSTRAINT fk_dismissal_family FOREIGN KEY (family_id) REFERENCES families(id) ON DELETE CASCADE,
    CONSTRAINT uq_dismissal_event_family UNIQUE (event_id, family_id)
);
