-- =====================================================================
-- V14__add_event_attendance.sql
--
-- Antes no había forma de apuntarse a un evento ni de ver cuántas
-- familias iban a asistir. Esta tabla es el opuesto de
-- event_dismissals: un registro aquí significa que la familia SÍ
-- quiere ir al evento, y permite mostrar el contador de asistentes.
-- =====================================================================

CREATE TABLE event_attendances (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    family_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_attendance_event FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE,
    CONSTRAINT fk_attendance_family FOREIGN KEY (family_id) REFERENCES families(id) ON DELETE CASCADE,
    CONSTRAINT uq_attendance_event_family UNIQUE (event_id, family_id)
);
