-- =====================================================================
-- V15__add_site_visits.sql
--
-- Contador de visitas privado para el panel de admin (mostrar tracción
-- real a Valencia Emprende / inversores). session_id es un UUID anónimo
-- generado en el navegador, sin datos personales ni IP guardada, para
-- poder medir visitantes únicos además de visitas totales.
-- =====================================================================

CREATE TABLE site_visits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR(64) NOT NULL,
    path VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_site_visits_session_id ON site_visits(session_id);
CREATE INDEX idx_site_visits_created_at ON site_visits(created_at);
