-- =====================================================================
-- V1__init_schema.sql
-- Baseline de esquema para LittleNeighbors en PostgreSQL.
-- Consolida las migraciones V1-V29 de MySQL (solo DDL).
-- Los datos de referencia van en V2__seed_reference_data.sql
-- =====================================================================

-- ---------------------------------------------------------------------
-- Función trigger que emula el ON UPDATE CURRENT_TIMESTAMP de MySQL
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ---------------------------------------------------------------------
-- cities (origen: V1)
-- ---------------------------------------------------------------------
CREATE TABLE cities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
-- Nota: a diferencia del resto de tablas, "cities" nunca tuvo
-- ON UPDATE CURRENT_TIMESTAMP en el original, así que no lleva trigger.

-- ---------------------------------------------------------------------
-- neighborhoods (origen: V1)
-- ---------------------------------------------------------------------
CREATE TABLE neighborhoods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    street_name VARCHAR(255) NOT NULL,
    postal_code VARCHAR(20),
    city_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_neighborhoods_city FOREIGN KEY (city_id) REFERENCES cities(id) ON DELETE CASCADE
);

CREATE INDEX idx_neighborhoods_city_id ON neighborhoods(city_id);
CREATE INDEX idx_neighborhoods_postal_code ON neighborhoods(postal_code);

CREATE TRIGGER trg_neighborhoods_updated_at
BEFORE UPDATE ON neighborhoods
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------
-- users (origen: V1, V2.1 añade verification_status/id_document_url,
-- V28 añade rejection_reason)
-- ---------------------------------------------------------------------
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    verification_status VARCHAR(50) NOT NULL DEFAULT 'UNVERIFIED',
    id_document_url VARCHAR(255),
    rejection_reason VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_users_email ON users(email);

CREATE TRIGGER trg_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------
-- user_roles (origen: V2)
-- ---------------------------------------------------------------------
CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role VARCHAR(50) NOT NULL,
    PRIMARY KEY (user_id, role),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- ---------------------------------------------------------------------
-- families (origen: V1; V11 hace neighborhood_id NOT NULL y quita el
-- ON DELETE SET NULL de la FK; V14/V15 añaden status; V25 añade lat/lon)
-- ---------------------------------------------------------------------
CREATE TABLE families (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    representative_name VARCHAR(255),
    family_name VARCHAR(255),
    description TEXT NOT NULL,
    profile_picture_url VARCHAR(255),
    neighborhood_id BIGINT NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'SURPRISE',
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_families_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_families_neighborhood FOREIGN KEY (neighborhood_id) REFERENCES neighborhoods(id)
);

CREATE INDEX idx_families_user_id ON families(user_id);
CREATE INDEX idx_families_neighborhood_id ON families(neighborhood_id);

CREATE TRIGGER trg_families_updated_at
BEFORE UPDATE ON families
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------
-- children (origen: V1; V9 hace birth_date/gender nullable y añade
-- soporte de embarazo; V16 amplía el CHECK de gender; V21 añade
-- description; V22 añade nickname NOT NULL)
-- ---------------------------------------------------------------------
CREATE TABLE children (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    birth_date DATE,
    gender VARCHAR(50),
    family_id BIGINT NOT NULL,
    life_stage VARCHAR(50) NOT NULL,
    is_pregnancy_support BOOLEAN NOT NULL DEFAULT FALSE,
    due_date DATE,
    is_prenatal BOOLEAN NOT NULL DEFAULT FALSE,
    description VARCHAR(500),
    nickname VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_children_family FOREIGN KEY (family_id) REFERENCES families(id) ON DELETE CASCADE,
    CONSTRAINT chk_gender CHECK (gender IN ('BOY', 'GIRL', 'PREGNANT'))
);

CREATE INDEX idx_children_family_id ON children(family_id);
CREATE INDEX idx_children_birth_date ON children(birth_date);
CREATE INDEX idx_children_gender ON children(gender);

CREATE TRIGGER trg_children_updated_at
BEFORE UPDATE ON children
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------
-- interests (origen: V1; V8 añade icon)
-- ---------------------------------------------------------------------
CREATE TABLE interests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(50) NOT NULL,
    icon VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_interest_type CHECK (type IN ('SPORTS', 'ARTS', 'MUSIC', 'SCIENCE', 'TECHNOLOGY', 'OUTDOOR', 'OTHER'))
);

CREATE INDEX idx_interests_type ON interests(type);
CREATE INDEX idx_interests_name ON interests(name);

CREATE TRIGGER trg_interests_updated_at
BEFORE UPDATE ON interests
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------
-- child_interests (origen: V1)
-- ---------------------------------------------------------------------
CREATE TABLE child_interests (
    child_id BIGINT NOT NULL,
    interest_id BIGINT NOT NULL,
    PRIMARY KEY (child_id, interest_id),
    CONSTRAINT fk_child_interests_child FOREIGN KEY (child_id) REFERENCES children(id) ON DELETE CASCADE,
    CONSTRAINT fk_child_interests_interest FOREIGN KEY (interest_id) REFERENCES interests(id) ON DELETE CASCADE
);

CREATE INDEX idx_child_interests_child_id ON child_interests(child_id);
CREATE INDEX idx_child_interests_interest_id ON child_interests(interest_id);

-- ---------------------------------------------------------------------
-- family_interests (origen: V14) - @ElementCollection, sin PK propia,
-- igual que en el original.
-- ---------------------------------------------------------------------
CREATE TABLE family_interests (
    family_id BIGINT NOT NULL,
    interest VARCHAR(255),
    CONSTRAINT fk_family_interests_family FOREIGN KEY (family_id) REFERENCES families(id) ON DELETE CASCADE
);

CREATE INDEX idx_family_interests_family_id ON family_interests(family_id);

-- ---------------------------------------------------------------------
-- matches (origen: V1; V6 renombra child_a_id/child_b_id a
-- child_request_id/child_target_id; V20 añade los campos de aceptación)
-- ---------------------------------------------------------------------
CREATE TABLE matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    child_request_id BIGINT NOT NULL,
    child_target_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    user_accepted BOOLEAN NOT NULL DEFAULT FALSE,
    neighbor_accepted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_matches_child_request FOREIGN KEY (child_request_id) REFERENCES children(id) ON DELETE CASCADE,
    CONSTRAINT fk_matches_child_target FOREIGN KEY (child_target_id) REFERENCES children(id) ON DELETE CASCADE,
    CONSTRAINT chk_match_status CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED')),
    CONSTRAINT chk_different_children CHECK (child_request_id <> child_target_id)
);

-- Nota: renombrados de idx_matches_child_a_id/idx_matches_child_b_id
-- a estos nombres para que coincidan con las columnas ya renombradas.
CREATE INDEX idx_matches_child_request_id ON matches(child_request_id);
CREATE INDEX idx_matches_child_target_id ON matches(child_target_id);
CREATE INDEX idx_matches_status ON matches(status);
CREATE UNIQUE INDEX idx_matches_unique_pair ON matches(child_request_id, child_target_id);

CREATE TRIGGER trg_matches_updated_at
BEFORE UPDATE ON matches
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------
-- events (origen: V10; V29 añade creator_family_id NOT NULL)
-- ---------------------------------------------------------------------
CREATE TABLE events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    event_date TIMESTAMP NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    neighborhood_id BIGINT,
    creator_family_id BIGINT NOT NULL,
    CONSTRAINT fk_event_neighborhood FOREIGN KEY (neighborhood_id) REFERENCES neighborhoods(id) ON DELETE SET NULL,
    CONSTRAINT fk_events_creator_family FOREIGN KEY (creator_family_id) REFERENCES families(id)
);

CREATE INDEX idx_event_location ON events(latitude, longitude);
CREATE INDEX idx_event_date ON events(event_date);

-- ---------------------------------------------------------------------
-- messages (origen: V17)
-- ---------------------------------------------------------------------
CREATE TABLE messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT NOT NULL,
    sender_id BIGINT NOT NULL,
    receiver_id BIGINT NOT NULL,
    match_id BIGINT,
    sent_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_messages_sender FOREIGN KEY (sender_id) REFERENCES users(id),
    CONSTRAINT fk_messages_receiver FOREIGN KEY (receiver_id) REFERENCES users(id),
    CONSTRAINT fk_messages_match FOREIGN KEY (match_id) REFERENCES matches(id) ON DELETE SET NULL
);

CREATE INDEX idx_messages_conversation ON messages(sender_id, receiver_id);
CREATE INDEX idx_messages_match_id ON messages(match_id);

CREATE TRIGGER trg_messages_updated_at
BEFORE UPDATE ON messages
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------
-- playdates (origen: V19)
-- ---------------------------------------------------------------------
CREATE TABLE playdates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    start_time TIMESTAMP NOT NULL,
    description TEXT,
    match_id BIGINT NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT fk_playdate_match FOREIGN KEY (match_id) REFERENCES matches(id) ON DELETE CASCADE
);

-- ---------------------------------------------------------------------
-- notifications (origen: V23)
-- ---------------------------------------------------------------------
CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_family_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    message VARCHAR(500) NOT NULL,
    type VARCHAR(50) NOT NULL,
    related_id BIGINT,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_notification_family FOREIGN KEY (recipient_family_id) REFERENCES families(id) ON DELETE CASCADE
);

-- ---------------------------------------------------------------------
-- pilot_leads (origen: V26; V27 añade invite_token/converted_at)
-- ---------------------------------------------------------------------
CREATE TABLE pilot_leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(150) NOT NULL,
    neighborhood VARCHAR(50) NOT NULL,
    invite_token VARCHAR(36) NOT NULL,
    converted_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX idx_pilot_leads_email_neighborhood ON pilot_leads(email, neighborhood);
CREATE UNIQUE INDEX idx_pilot_leads_invite_token ON pilot_leads(invite_token);