ALTER TABLE users
MODIFY COLUMN first_name VARCHAR(255) NOT NULL,
MODIFY COLUMN last_name VARCHAR(255) NOT NULL;

ALTER TABLE users
ADD COLUMN verification_status VARCHAR(50) NOT NULL DEFAULT 'UNVERIFIED',
ADD COLUMN id_document_url VARCHAR(255) DEFAULT NULL;

UPDATE users
SET verification_status = 'VERIFIED';